apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment
  labels:
    app: test-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: test-deploy
  template:
    metadata:
      labels:
        app: test-deploy
    spec:
      containers:
      - name: app-container
        image: ${{ vars.DOCKERHUB_USERNAME }}/jlv-project:${{ env.sha }}
        resources:
        requests:
          cpu: "500m"          # Minimum CPU required (adjust as needed)
          memory: "2Gi"        # Minimum memory required
        limits:
          cpu: "2000m"         # Maximum CPU allowed
          memory: "4Gi"        # Maximum memory allowed
        ports:
        - containerPort: 8080


        
