apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment-cicd
  labels:
    app: test-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: test-deploy
  template:
    metadata:
      labels:
        app: test-deploy
    spec:
      containers:
      - name: app-container
        image: violalag/jlv-project:latest
        resources:
          limits:
              memory: "512Mi"
              cpu: "500m"
          requests:
              memory: "256Mi"
              cpu: "250m"      
        ports:
        - containerPort: 8080

        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10
        
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 15


        
