apiVersion: v1
kind: Service
metadata:
  name: test-service-cicd
spec:
  selector:
    app: test-deploy
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30000   # The node port on which your service will be accessible
  type: NodePort
