name: Lint Code Base

on: 
  push:
    branches:
    - main
  pull_request:
    branches : 
    - main

env:
  DOCKER_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/jlv-project
  K8S_NAMESPACE: default
  DEPLOYMENT_NAME: test-deployment-cicd

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: read
      # To report GitHub Actions status checks
      statuses: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Super-linter
        uses: super-linter/super-linter@v7.0.0 # x-release-please-version
        env:
          DEFAULT_BRANCH : main
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_HTML : true
          VALIDATE_JAVASCRIPT_ES	: true
          VALIDATE_PYTHON : true
          # To report GitHub Actions status checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test-deploy:
    name : Build Docker Image and Deploy to Kubernetes
    runs-on: ubuntu-latest
    permissions:
        contents: read
        packages: read
        # To report GitHub Actions status checks
        statuses: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Docker Login
        uses: docker/login-action@v3
        with:
              username: ${{ secrets.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Get Short Git SHA
        id: vars
        run: echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      
      - name: Build and push container image
        uses: docker/build-push-action@v6
        with:
                push: true
                tags: |
                  ${{ env.DOCKER_IMAGE }}:${{ env.sha }}
                  ${{ env.DOCKER_IMAGE }}:latest

      - name: Set up kind
        uses: helm/kind-action@v1.6.0
        with:
              version: v0.20.0
          
      - name: Create kind Cluster
        run: kind create cluster --name kind
            
      - name: Verify kind Cluster
        run: kind get clusters
        
      - name: Configure kubectl for kind
        run: |
              kubectl cluster-info --context kind-kind
      
      - name: Apply Kubernetes Manifests
        run: |
                kubectl apply -f k8s/deployment.yaml
                kubectl apply -f k8s/service.yaml

      - name: Verify Deployment Exists
        run: |
              kubectl get deployments -n ${{ env.K8S_NAMESPACE }}
              kubectl get pods -n ${{ env.K8S_NAMESPACE }}
              kubectl get services -n ${{ env.K8S_NAMESPACE }}
              
      - name: Deploy to Kubernetes
        run: |
            kubectl set image deployment/${{ env.DEPLOYMENT_NAME }} -n ${{ env.K8S_NAMESPACE }} app-container=${{ env.DOCKER_IMAGE }}:${{ env.sha }}
            kubectl rollout status deployment/${{ env.DEPLOYMENT_NAME }} -n ${{ env.K8S_NAMESPACE }}
            
      - name: Verify Service Details
        run: |
          kubectl get svc test-service-cicd -n default
      
      - name: Verify Pod Logs
        run: |
              kubectl logs test-deployment-cicd-$(kubectl get pods -l app=test-deploy -n default -o=jsonpath='{.items[0].metadata.name}') -n default

      - name: Verify Pod Listening Ports
        run: |
              kubectl exec -it test-deployment-cicd-$(kubectl get pods -l app=test-deploy -n default -o=jsonpath='{.items[0].metadata.name}') -n default -- netstat -tuln
            
      - name: Health Check
        run: |
            kubectl wait --for=condition=ready pod -l app=test-deploy -n ${{ env.K8S_NAMESPACE }} --timeout=480s
      
      - name: Access Service via NodePort
        run: |              
              KIND_NODE_IP=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' kind-control-plane)
              NODE_PORT=30080
              sleep 5
              curl http://$KIND_NODE_IP:$NODE_PORT/health || curl http://localhost:$NODE_PORT/health

